Update mentoring.md
exercism/website-copy pull request #1570
Opened 2020-04-27 19:31 UTC by Eiermann

Added a short solution using Enum.frequencies.

2020-09-16 13:05 UTC, SleeplessByte commented on tracks/elixir/exercises/word-count/mentoring.md
> +```
````suggestion
```

````

2020-09-16 15:17 UTC, NobbZ requested changes
Even though `Enum.frequencies/1,2` exists, I'm not really sure if it is within "first principles" or a valid use of standard library…

Also we have to remember, that not everyone already has access to elixir 1.10, and therefore they might not have access to this function, as it has been added with 1.10.

Therefore I think it should not only the example added, but the use of `Enum.frequencies/1,2` could be something to talk about, but nothing that would actually block a students progress.

2020-09-16 15:17 UTC, NobbZ commented on tracks/elixir/exercises/word-count/mentoring.md
> +
```suggestion

```

2020-09-16 15:17 UTC, NobbZ commented on tracks/elixir/exercises/word-count/mentoring.md
> +```elixir
```suggestion

```elixir
```

2020-12-14 14:23 UTC, NobbZ approved these changes

2020-12-14 16:30 UTC, merged

2020-12-14 16:30 UTC, SleeplessByte commented
Thanks @NobbZ for re-checking.