Update b.json
exercism/website-copy pull request #1731
Opened 2020-09-13 14:25 UTC by bubo-py

Added myself to python mentors

2020-09-13 15:07 UTC, NobbZ requested changes

2020-09-13 15:07 UTC, NobbZ commented on mentors/python/b.json
> +    "link_text" : "My Github",
```suggestion
    "link_text" : "My GitHub",
```

Please use correct spelling of GitHub here.

2020-09-13 15:55 UTC, rpottsoh approved these changes

2020-09-13 17:34 UTC, NobbZ approved these changes

2020-09-16 12:52 UTC, merged

2020-09-16 12:53 UTC, SleeplessByte commented
Welcome to Python 🐍 !