Add mentor bio for ansumanbebarta
exercism/website-copy pull request #1754
Opened 2020-09-30 09:58 UTC by ansumanbebarta

2020-09-30 13:58 UTC, rpottsoh requested changes

2020-09-30 13:58 UTC, rpottsoh commented on mentors/python/a.json
>    }
```suggestion
  },
```
Missing a comma.

2020-09-30 18:36 UTC, rpottsoh commented
@ansumanbebarta your second commit fixed the issue.  Your third commit has added your bio a second time.

2020-09-30 19:05 UTC, ansumanbebarta commented
This was my first PR ever, so I was unaware of the process of updating a PR.  I am sorry for the inconvenience.

2020-09-30 20:41 UTC, hugovk commented
I don't think you are a mentor for this project.

Please don't create spam PRs for Hacktoberfest, it's against the rules and values, and not fair on maintainers.

https://hacktoberfest.digitalocean.com/details#spam

Maintainers: please label this `invalid` so it's not counted towards Hacktoberfest.

2020-10-01 01:05 UTC, neenjaw commented
Hey @hugovk, there really isn't a good way to externally see if someone is or isn't an active mentor on Exercism as many good mentors aren't overly active on github or in the exercism slack chat, so they operate in relative obscurity. @ihid is probably best to sort this out as he is the founder and can do some investigation/asking around.

I can see where you are coming from though, there has been a flurry across the whole of github to make low-quality PRs, but I am not sure this one is so straightforward.

2020-10-01 03:16 UTC, SleeplessByte approved these changes

2020-10-01 03:16 UTC, SleeplessByte commented
Welcome to Python 🐍

2020-10-01 03:16 UTC, merged

2020-10-01 12:36 UTC, iHiD commented
@ansumanbebarta This wasn't a fun process for you. I'm sorry. Thank you for being a mentor. You should receive an invitation to Slack too. Please say hello when you get there :) I'm @iHiD 1-1.

@hugovk Thank you for trying to help, but please leave the Hacktoberfest "policing" to the senior maintainers team.

2020-10-01 16:22 UTC, hugovk commented
I'd like to sincerely apologise, I was off mark.

I wish you all the best and hope this doesn't put you off!

2020-10-01 18:48 UTC, iHiD commented
Thanks @hugovk 💙