add mentor nathalier
exercism/website-copy pull request #1781
Opened 2020-10-04 16:12 UTC by nathalier

2020-10-04 16:54 UTC, rpottsoh requested changes

2020-10-04 16:54 UTC, rpottsoh commented on mentors/python/n.json
> +    "link_url": " ",
URL cannot be white space.  Should be `null` if you do not have a link you wish to share.

2020-12-14 12:20 UTC, SleeplessByte commented
Pinging @nathalier

2022-03-04 09:19 UTC, DanielNoord commented on mentors/python/n.json
> +    "link_url": " ",
```suggestion
    "link_url": null,
```

2022-03-04 19:22 UTC, BethanyG commented
Pinging @nathalier -- this branch has merge conflicts and requested changes that need to be resolved.  

In the interest of cleaning out PRs from this repo that are older than 8 months, I'll wait a week to hear from you and then close this PR.  Let us know if you have any questions or issues.  Thanks!

2022-03-04 21:03 UTC, angelikatyborska commented
Is this PR even still necessary? I thought adding mentors via those JSON files is deprecated in v3. It all happens via the platform now.

2022-03-04 21:07 UTC, BethanyG commented
🤦🏽‍♀️   **_you are so right, @angelikatyborska!_**  Thank you for the reminder.  Closing.  😄

2022-03-04 21:07 UTC, closed without merging