Update b.json
exercism/website-copy pull request #1795
Opened 2020-10-23 10:19 UTC by bobahop

Add Bob Hoeppner to Rust mentors

2020-10-23 20:05 UTC, rpottsoh requested changes
Url must be a filled in completely.  If you want the link to appear differently on the site then also fill in "link_text" as well.

2020-10-23 20:05 UTC, rpottsoh commented on mentors/rust/b.json
> +    "link_url": "github.com/bobahop",
```suggestion
    "link_url": "https://www.github.com/bobahop",
```

2020-10-23 21:03 UTC, bobahop commented
Thanks for the correction!

2020-10-24 11:48 UTC, rpottsoh approved these changes

2020-10-24 11:49 UTC, merged