[Javascript] Add mentor
exercism/website-copy pull request #1964
Opened 2021-04-12 20:10 UTC by mateus4k

2021-04-12 23:43 UTC, rpottsoh requested changes

2021-04-12 23:43 UTC, rpottsoh commented on mentors/javascript/m.json
> +   {
Parens should line up.  Please remove one leading space.

2021-04-12 23:51 UTC, mateus4k commented
Thanks for the review, @rpottsoh 🙂

2021-04-13 00:38 UTC, rpottsoh approved these changes

2021-04-13 00:38 UTC, merged