Update mentoring.md
exercism/website-copy pull request #1988
Opened 2021-05-21 17:32 UTC by richarda23

A student had added try/catch blocks to their solution,  presumably to deal with these exceptions, but handled them incorrectly. Exception handling is a tricky concept for beginners so feel some advice here is useful.

2022-03-07 18:25 UTC, ericbalawejder approved these changes

2022-03-07 18:57 UTC, kotp requested changes

2022-03-07 18:57 UTC, kotp commented on tracks/java/exercises/gigasecond/mentoring.md
> +`plusSeconds` can throw a `java.time.DateTimeException`. A student may choose to  catch this exception in the constructor, but this results in  `birthDateTime` being null, so the class won't have bee
```suggestion
`plusSeconds` can throw a `java.time.DateTimeException`.
A student may choose to catch this exception in the constructor, but this results in `birthDateTime` being null, so the class won't have been instantiated properly.
There's no sensible default value that be stored in `birthDateTime`.
It's better to let the exception be thrown, failing fast, and let calling code deal with it. 
```

Single sentence per line, and removed some duplicate spaces. (I did this in the text area, so I might have missed some.)

2022-03-07 18:58 UTC, kotp commented on tracks/java/exercises/gigasecond/mentoring.md
> +`plusSeconds` can throw a `java.time.DateTimeException`. A student may choose to  catch this exception in the constructor, but this results in  `birthDateTime` being null, so the class won't have bee
The last sentence could be written better, I think.

"It's better to let the exception be thrown, failing fast, letting the calling code deal with it."

2024-02-16 09:01 UTC, SleeplessByte approved these changes

2024-02-16 09:01 UTC, merged