Handle the edge-case of an empty scores list
exercism/website-copy pull request #2015
Opened 2021-07-08 21:00 UTC by Arpanio

The canonical solution throws a ValueError or an IndexError in case of empty scores list. Updated code to handle this edge case.

2021-09-05 18:45 UTC, IsaacG requested changes

2021-09-05 18:45 UTC, IsaacG commented on tracks/python/exercises/high-scores/mentoring.md
> +  def latest(scores):
What would be the expected return type of this function?

2021-09-05 18:45 UTC, IsaacG commented on tracks/python/exercises/high-scores/mentoring.md
> +      return []
What would be the expected return type of this function?

2022-03-04 19:18 UTC, BethanyG commented
@Arpanio - are you still interested in working on this PR?  

If so, please see/address the questions posed by @IsaacG above.  Thanks!

2022-06-27 18:51 UTC, BethanyG commented
Closing, since there was no reply from OP.

2022-06-27 18:51 UTC, closed without merging