Update t.json
exercism/website-copy pull request #2032
Opened 2021-07-28 08:02 UTC by teto1992

added bio

2021-07-28 14:15 UTC, rpottsoh requested changes

2021-07-28 14:15 UTC, rpottsoh commented on mentors/prolog/t.json
> +}
```suggestion
    "github_username": "teto1992",
    "name": "Stefano Forti",
    "link_text": "Personal site",
    "link_url": "http://pages.di.unipi.it/forti/",
    "avatar_url": "http://pages.di.unipi.it/forti/assets/images/profile.jpg",
    "bio": "Post-doc researcher and Pisa CoderDojo founder and mentor. I use Prolog for fast (and clean!) prototyping of my research and fun ideas. I really enjoy mentoring people in improving their programming skills!"
  }
```
Just a minor change request.

2021-07-29 09:29 UTC, teto1992 commented
change accepted

2021-07-29 09:42 UTC, teto1992 reviewed
change accepted :-)

2021-07-30 13:20 UTC, rpottsoh approved these changes

2021-07-30 13:21 UTC, merged