Correct error in mentoring help
exercism/website-copy pull request #2256
Opened 2023-04-25 12:41 UTC by safwansamsudeen

This is in response to [this issue](https://forum.exercism.org/t/error-in-sum-of-multiples-mentoring-suggestion/5388) on the forum.

2023-04-25 14:43 UTC, IsaacG submitted a review, later dismissed

2023-04-25 17:52 UTC, BethanyG requested changes
The Python track style is to not use single letter variable names - not even in comprehensions.  I know it is widely done (_and we can probably find numerous cases in mentor notes and documentation where that rule has not been followed_) - but I'd like to not add any new instances.

2023-04-27 03:18 UTC, IsaacG approved these changes

2023-04-28 16:49 UTC, BethanyG commented
@safwansamsudeen  - as far as I can see this still has `n` as a variable name.

2023-04-29 02:31 UTC, safwansamsudeen commented
@BethanyG My bad, I assumed that I only had to change `m`.

2023-05-09 16:32 UTC, BethanyG approved these changes

2023-05-09 16:32 UTC, merged